<a href="https://colab.research.google.com/github/alexanechka/linalg/blob/main/linalg_homework02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


##Линейная алгебра##
###Практическое задание к уроку 2.1##

In [ ]:
import numpy as np
import scipy.linalg
import math

__1.__ Установить, какие произведения матриц $AB$ и $BA$ определены$AB$ и $BA$ определены, и найти размерности полученных матриц:

   а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$;

   Произведения $AB$ и $BA$ не определены, т.к. матрицы содержат 4 строки и 2 столбца

    
   б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;

   Произведение $AB$ не определено, т.к. матрица $A$ содержит 2 строки, а матрица $B$ - 3 столбца. Произведение $BA$ определено, размер полученной матрицы $2\times 3$
    
   в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;
   
   Произведение $AB$ определено, размер полученной матрицы $3\times 3$  Произведение $BA$ определено, размер полученной матрицы $8\times 8$  
    
   г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.
   
   Произведения $AB$ и $BA$ определены, размер полученных матриц $4\times 4$

In [ ]:
A = np.array([[1, -2], [3, 0], [5, 5],[4,6],[6,2]])
B = np.array([[4, -1, 5,3,1], [0, 5,2,1,3], [1,2,3,2,1]])
print('Matrix A ', A)
print('Matrix B ', B)
# print ('A @ B ', A @ B)
print ('B @ A ', B @ A) 

Matrix A  [[ 1 -2]
 [ 3  0]
 [ 5  5]
 [ 4  6]
 [ 6  2]]
Matrix B  [[ 4 -1  5  3  1]
 [ 0  5  2  1  3]
 [ 1  2  3  2  1]]
B @ A  [[44 37]
 [47 22]
 [36 27]]


In [ ]:
B = np.array([[1, -2, 7], [3, 0, 9], [5, 5, 1],[4,6, 2],[6,2, 7], [4, 8, 9],[5,2, 9],[0,9,2]])
A = np.array([[4, -1, 5,3,1,5,4,5], [0, 5,2,1,3,3,2,2], [1,2,3,2,1,2,1,2]])
print('Matrix A ', A)
print('Matrix B ', B)
print ('A @ B ', A @ B)
print ('B @ A ', B @ A) 

Matrix A  [[ 4 -1  5  3  1  5  4  5]
 [ 0  5  2  1  3  3  2  2]
 [ 1  2  3  2  1  2  1  2]]
Matrix B  [[ 1 -2  7]
 [ 3  0  9]
 [ 5  5  1]
 [ 4  6  2]
 [ 6  2  7]
 [ 4  8  9]
 [ 5  2  9]
 [ 0  9  2]]
A @ B  [[ 84 130 128]
 [ 69  68 119]
 [ 49  63  70]]
B @ A  [[11  3 22 15  2 13  7 15]
 [21 15 42 27 12 33 21 33]
 [21 22 38 22 21 42 31 37]
 [18 30 38 22 24 42 30 36]
 [31 18 55 34 19 50 35 48]
 [25 54 63 38 37 62 41 54]
 [29 23 56 35 20 49 33 47]
 [ 2 49 24 13 29 31 20 22]]


__2.__ Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$


$A + B=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix} + \begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix} = \begin{pmatrix}
5 & -3\\ 
3 & 5
\end{pmatrix}$


In [ ]:
A = np.array([[1, -2], [3, 0]])
B = np.array([[4, -1], [0, 5]])
print('Matrix A ', A)
print('Matrix B ', B)
print ('A + B ', A + B)

Matrix A  [[ 1 -2]
 [ 3  0]]
Matrix B  [[ 4 -1]
 [ 0  5]]
A + B  [[ 5 -3]
 [ 3  5]]


__3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$

$ 3A-2B+4C = 3 \cdot \begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix} - 2 \cdot \begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix} + 4 \cdot \begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix} = \begin{pmatrix}
3 & 21\\ 
9 & -18
\end{pmatrix} + \begin{pmatrix}
0 & -10\\ 
-4 & 2
\end{pmatrix}  + \begin{pmatrix}
8 & -16\\ 
4 & 4
\end{pmatrix} = \begin{pmatrix}
11 & -5\\ 
9 & -12
\end{pmatrix}$

In [ ]:
A = np.array([[1, 7], [3, -6]])
B = np.array([[0, 5], [2, -1]])
C = np.array([[2, -4], [1, 1]])
print('Matrix A ', A)
print('Matrix B ', B)
print('Matrix C ', C)
print ('3*A - 2 * B + 4 * C ', 3*A - 2 * B + 4 * C)

Matrix A  [[ 1  7]
 [ 3 -6]]
Matrix B  [[ 0  5]
 [ 2 -1]]
Matrix C  [[ 2 -4]
 [ 1  1]]
3*A - 2 * B + 4 * C  [[ 11  -5]
 [  9 -12]]


__4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.

$A^{T} = \begin{pmatrix}
4 & 5 & 2\\ 
1 & -2 & 3
\end{pmatrix}$

$ AA^{T} = \begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix} \cdot \begin{pmatrix}
4 & 5 & 2\\ 
1 & -2 & 3
\end{pmatrix} = \begin{pmatrix}
16 + 1 & 20 -2 & 8 + 3\\ 
20 - 2 & 25 + 4 & 10 - 6\\ 
8 + 3 & 10 - 6 & 4 + 9
\end{pmatrix} = \begin{pmatrix}
17 & 18 & 11\\ 
18 & 29 & 4\\ 
11 & 4 & 13
\end{pmatrix}$

$ A^{T}A = \begin{pmatrix}
4 & 5 & 2\\ 
1 & -2 & 3
\end{pmatrix} \cdot \begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}  = \begin{pmatrix}
16 + 25 + 4 & 4 -10 + 6\\ 
4 - 10 + 6 & 1 + 4 + 9
\end{pmatrix} = \begin{pmatrix}
45 & 0\\  
0 & 14
\end{pmatrix}$

In [ ]:
A = np.array([[4, 1], [5, -2], [2, 3]])
print('Matrix A ', A)
print('Matrix AT ', A.T)
print('A * AT ', A @ A.T)
print ('AT * A', A.T @ A)

Matrix A  [[ 4  1]
 [ 5 -2]
 [ 2  3]]
Matrix AT  [[ 4  5  2]
 [ 1 -2  3]]
A * AT  [[17 18 11]
 [18 29  4]
 [11  4 13]]
AT * A [[45  0]
 [ 0 14]]


###Практическое задание к уроку 2.2##

__1.__ Вычислить определитель:

   a)

$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix};$$

$ det \begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix} = sin x \cdot sin x - cos x \cdot (-cosx) = sin ^2 x + cos ^2 x = 1$

   б)
    
$$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix};$$

$ det \begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix} = 4 \cdot \begin{vmatrix}
 5 & 1\\ 
 0 & 9
\end{vmatrix} - 0 \cdot \begin{vmatrix}
2 & 3\\ 
0 & 9
\end{vmatrix} + 0 \cdot \begin{vmatrix}
2 & 3\\ 
 5 & 1
\end{vmatrix} = 4 \cdot (5 \cdot 9 - 0 \cdot 1) = 180$

    
   в)

$$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}.$$

$ det \begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix} = 1 \cdot \begin{vmatrix}
 5 & 6\\ 
 8 & 9
\end{vmatrix} - 2 \cdot \begin{vmatrix}
4 & 6\\ 
7 & 9
\end{vmatrix} + 3 \cdot \begin{vmatrix}
4 & 5\\ 
7 & 8
\end{vmatrix} = 1 \cdot (5 \cdot 9 - 6 \cdot 8) - 2 \cdot (4 \cdot 9 - 6 \cdot 7) + 3 \cdot (4 \cdot 8 - 7 \cdot 5)= 45 - 48 - 2 \cdot (36 - 42) + 3 \cdot (  32 - 35) = -3 + 12 - 9 = 0$

In [ ]:
x = 5
A = np.array([[math.sin(x), -math.cos(x)], [math.cos(x), math.sin(x)]])
print('Matrix A ', A)
print ('det(A)', np.linalg.det(A), '\n')

B = np.array([[4, 2, 3], [0, 5, 1], [0,0,9]])
print('Matrix B ', B)
print ('det(B)', np.linalg.det(B), '\n')

C = np.array([[1, 2, 3], [4, 5, 6], [7,8,9]])
print('Matrix C ', C)
print ('det(C)', np.linalg.det(C), '\n')

Matrix A  [[-0.95892427 -0.28366219]
 [ 0.28366219 -0.95892427]]
det(A) 1.0 

Matrix B  [[4 2 3]
 [0 5 1]
 [0 0 9]]
det(B) 180.0 

Matrix C  [[1 2 3]
 [4 5 6]
 [7 8 9]]
det(C) 0.0 



__2.__ Определитель матрицы $A$ равен $4$. Найти:

   а) $det(A^{2})$;

   $det(AB)=detA\cdot detB ⇒ det(A^{2}) = 4 \cdot 4 = 16 $
   $$$$ 
   б) $det(A^{T})$;

   $detA^{T}=detA ⇒ det(A^{T}) = 4$ 
   $$$$
    
   в) $det(2A)$.
   
   Умножение строки или столбца матрицы на число  λ  приведет к умножению определителя матрицы на то же число $⇒ det(2A) = 8 $


__3.__  Доказать, что матрица

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная.
$$$$
Вырожденной называется матрица, определитель которой равен 0.
$det \begin{vmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{vmatrix} = -2 \cdot \begin{vmatrix}
 -14 & 6\\ 
7 & 13
\end{vmatrix} - 4 \cdot \begin{vmatrix}
 7 & -3\\  
 7 & 13
\end{vmatrix}  - 3 \cdot  \begin{vmatrix}
 7 & -3\\ 
 -14 & 6
\end{vmatrix} =$
$= -2 \cdot (-14 \cdot 13 - 7 \cdot 6) - 4 \cdot (7 \cdot 13 + 21) - 3 \cdot ( 7 \cdot 6 - 14 \cdot 3) =$
$ = 2 \cdot 14 \cdot 13 + 2 \cdot 7 \cdot 6 - 2 \cdot 14 \cdot 13 - 4 \cdot 21 - 3 \cdot 0 = 2 \cdot 14 \cdot 13 - 2 \cdot 14 \cdot 13 + 2 \cdot 21 \cdot 2  - 4 \cdot 21 = 0  $


In [ ]:
A = np.array([[-2, 7, -3], [4, -14 , 6], [-3, 7 ,13]])
print('Matrix A ', A)
print ('det(A)', np.linalg.det(A), '\n')


Matrix A  [[ -2   7  -3]
 [  4 -14   6]
 [ -3   7  13]]
det(A) 0.0 



__4.__ Найти ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$
$$$$
Третья строка равняется сумме первой и второй строки, значит ее можно отбросить.

$\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1
\end{pmatrix}$

Таким образом, ранг матрицы равен  2.
$$$$

   б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$
$$$$
Третья строка равняется сумме первой и второй строки, значит ее можно отбросить.

$\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$

Таким образом, ранг матрицы равен  3.

In [ ]:
A = np.array([[1,2,3],[1,1,1], [2,3,4]])
r = np.linalg.matrix_rank(A)

print(f'Ранг матрицы: {r}', '\n')

B = np.array([[0,0,2,1],[0,0,2,2], [0,0,4,4], [2,3,5,6]])
r_1 = np.linalg.matrix_rank(B)

print(f'Ранг матрицы: {r_1}', '\n')


Ранг матрицы: 2 

Ранг матрицы: 3 

